# Generated by Django 6.1 on 2026-09-04 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="views",
            new_name="views_article",
        ),
    ]
