# Generated by Django 6.1 on 2026-08-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactsShop",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("country", models.CharField(default="Россия", max_length=100, verbose_name="Страна")),
                ("inn", models.CharField(default=-1234244, max_length=20, verbose_name="ИНН")),
                (
                    "address",
                    models.CharField(
                        default="Москва, Якиманка, Ленинский проспект 1А<", max_length=200, verbose_name="Адрес"
                    ),
                ),
            ],
            options={
                "verbose_name": "Контакт магазина",
                "verbose_name_plural": "Контакты магазина",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(max_length=250, verbose_name="Описание категории"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.TextField(max_length=100, verbose_name="Наименование категории"),
        ),
    ]
