# Generated by Django 6.1 on 2026-09-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_contactsshop_alter_category_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactsshop",
            name="address",
            field=models.CharField(
                default="Москва, Якиманка, Ленинский проспект 1А", max_length=200, verbose_name="Адрес"
            ),
        ),
        migrations.AlterField(
            model_name="contactsshop",
            name="inn",
            field=models.CharField(default="77-1234321", max_length=20, verbose_name="ИНН"),
        ),
    ]
