# Generated by Django 6.1 on 2026-09-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_contactsshop_address_alter_contactsshop_inn"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name"],
                "permissions": [("can_unpublish_product", "Can unpublish product")],
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="publication_status",
            field=models.BooleanField(default=False, verbose_name="Статус публикации"),
        ),
    ]
